version: '3'

services:
  dbadmin:
    image: phpmyadmin
    container_name: dbadmin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - bnet
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=bnet"
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"      

networks:
  bnet:
    external: true